FROM python:3.11-slim

WORKDIR /app

COPY services/enricher/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY services/enricher ./services/enricher
COPY services/kafka ./services/kafka
COPY services/dal ./services/dal
COPY services/utils/logger.py ./services/utils/logger.py
COPY services/config.py ./services/config.py

CMD ["python", "-m", "services.enricher.main"]

