FROM python:3.11-slim

WORKDIR /app

COPY services/persister/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY  podcasts ./podcasts
COPY services/persister ./services/persister
COPY services/kafka ./services/kafka
COPY services/dal ./services/dal
COPY services/utils ./services/utils
COPY services/config.py ./services/config.py

CMD ["python", "-m", "services.persister.main"]

